Repository bitwarden/workflow-linter, pull requests merged in 2025-05, with the labels that each got.

#115 Remove launchdarkly/find-code-references-in-pull-request action
  src/bitwarden_workflow_linter/default_actions.json
Labels: version:patch

#117 BRE-609/scan-update
  .github/workflows/scan.yml
Labels: version:skip

#118 BRE-609/check-pr-target-rule-update
  .github/workflows/examples/ci.yaml
  .github/workflows/examples/pull_request_target.yml
  settings.yaml
  src/bitwarden_workflow_linter/default_settings.yaml
  src/bitwarden_workflow_linter/rules/check_pr_target.py
  src/bitwarden_workflow_linter/utils.py
  tests/rules/test_check_pr_target.py
Labels: version:patch

#119 [BRE-827] Allow permissions to be set on all jobs or workflow level
  src/bitwarden_workflow_linter/models/job.py
  src/bitwarden_workflow_linter/rules/permissions_exist.py
  tests/rules/test_permissions_exist.py
Labels: version:minor

#121 [BRE-828] Reverting to 3.12 for install
  .github/workflows/bwwl_operations.yml
Labels: version:minor

#120 BRE-609/flip-pr-target-rule-to-error
  README.md
  settings.yaml
  src/bitwarden_workflow_linter/default_settings.yaml
Labels: version:patch

#124 BRE-840/fix-pypi-version
  .github/workflows/cd.yml
Labels: version:patch

#129 [BRE-849] - Make Lint Command Take More Than One Argument
  src/bitwarden_workflow_linter/cli.py
  src/bitwarden_workflow_linter/lint.py
Labels: version:minor

#130 [BRE-727] - Activate Permission Rule Error
  settings.yaml
  src/bitwarden_workflow_linter/default_settings.yaml
Labels: version:skip
