Repository bitwarden/workflow-linter, pull requests merged in 2025-01, with the labels that each got.

#40 [BRE-494] - Update Approved Actions
  src/bitwarden_workflow_linter/default_actions.json
Labels: version:patch

#42 Update README
  README.md
Labels: version:patch

#43 Use GitHub App token
  .github/workflows/cd.yml
  .github/workflows/enforce-labels.yml
Labels: version:patch

#45 Add actions/setup-go action to list of approved actions
  src/bitwarden_workflow_linter/default_actions.json
Labels: version:patch

#47 [BRE-534] Update the CD workflow to not run in a loop
  .github/workflows/cd.yml
Labels: version:patch

#46 [BRE-544] Add skip version bump type
  .github/workflows/cd.yml
  .github/workflows/enforce-labels.yml
Labels: version:patch

#44 [BRE-541] Handling steps where no comment is added to uses
  src/bitwarden_workflow_linter/models/step.py
  tests/rules/test_step_approved.py
  tests/test_step.py
Labels: version:patch

#49 Add Astro Action
  src/bitwarden_workflow_linter/default_actions.json
Labels: version:patch

#39 Add actionlint to workflow linter
  .gitignore
  README.md
  settings.yaml
  src/bitwarden_workflow_linter/default_settings.yaml
  src/bitwarden_workflow_linter/load.py
  src/bitwarden_workflow_linter/models/workflow.py
  src/bitwarden_workflow_linter/rules/run_actionlint.py
  tests/fixtures/test_workflow.yaml
  tests/fixtures/test_workflow_incorrect.yaml
  tests/rules/test_run_actionlint.py
  tests/test_workflow.py
Labels: enhancement, version:minor

#50 Fastly Compute actions
  src/bitwarden_workflow_linter/default_actions.json
Labels: version:patch

#48 Update SonarQube GitHub Action
  .github/workflows/scan.yml
Labels: version:patch

#51 Agalles/approve docker
  src/bitwarden_workflow_linter/default_actions.json
Labels: enhancement, version:patch

#56 Add actions used in Secret Manager SDK to the approved actions list
  src/bitwarden_workflow_linter/default_actions.json
Labels: version:patch

#58 [BRE-546] - Disable Approved Actions
  settings.yaml
  src/bitwarden_workflow_linter/default_actions.json
  src/bitwarden_workflow_linter/default_settings.yaml
Labels: version:patch
