Repository bitwarden/workflow-linter, pull requests merged in 2025-02, with the labels that each got.

#62 Enabled SonarQube scanning for PRs
  .github/workflows/scan.yml
Labels: version:patch

#64 Fix renovate config
  .github/renovate.json
Labels: version:skip

#59 [BRE-553] adding rule and test for check-run
  settings.yaml
  src/bitwarden_workflow_linter/default_settings.yaml
  src/bitwarden_workflow_linter/models/job.py
  src/bitwarden_workflow_linter/rules/check_pr_target.py
  tests/rules/test_check_pr_target.py
Labels: enhancement, version:minor

#67 Fix parenthesis on if key for Enforce Labels workflow
  .github/workflows/enforce-labels.yml
Labels: version:skip

#66 Change the version to 0.7.0
  src/bitwarden_workflow_linter/__about__.py
Labels: version:skip

#55 Updated docker/build-push-action to 6.12.0
  src/bitwarden_workflow_linter/default_actions.json
Labels: version:patch

#54 Updated actions/upload-artifact to 4.6.0
  src/bitwarden_workflow_linter/default_actions.json
Labels: version:patch

#69 [BRE-595] - Implement Add Actions Workflow
  .github/CODEOWNERS
  .github/workflows/bwwl_operations.yml
Labels: version:minor

#52 Update SonarQube and CodeCov action versions
  src/bitwarden_workflow_linter/default_actions.json
Labels: version:patch

#73 bwwl operation review
  .github/workflows/bwwl_operations.yml
Labels: version:skip

#75 Fix workflow id error
  .github/workflows/bwwl_operations.yml
Labels: version:skip

#70 Add rule rollout document
  README.md
  RULE_ROLLOUT.md
Labels: version:skip

#77 Fix condition typo
  .github/workflows/bwwl_operations.yml
Labels: version:skip

#78 Fix app token
  .github/workflows/bwwl_operations.yml
Labels: version:skip

#76 [BRE-632] New workflow to scan examples
  .github/workflows/examples/ci.yaml
  .github/workflows/examples/example-references/_build.yml
  .github/workflows/examples/example-references/_docker.yml
  .github/workflows/examples/example-references/_test.yml
  .github/workflows/examples/example-references/_version.yml
  .github/workflows/examples/example.yaml
  .github/workflows/examples/scan.yaml
  .github/workflows/lint-examples.yml
Labels: version:minor
