Repository bitwarden/workflow-linter, pull requests merged in 2025-04, with the labels that each got.

#90 BRE-743/update-bwwl-readme
  .python-version
  README.md
Labels: version:skip

#85 try splitting up check_actionlint
  src/bitwarden_workflow_linter/rules/run_actionlint.py
  tests/rules/test_run_actionlint.py
Labels: enhancement, version:minor

#100 bump actionlint version and track with renovate
  .github/CODEOWNERS
  .github/renovate.json
  actionlint_version.json
  src/bitwarden_workflow_linter/rules/run_actionlint.py
Labels: version:patch

#102 temporary fix for actionlint versioning
  src/bitwarden_workflow_linter/rules/run_actionlint.py
Labels: version:skip

#103 add comment and version patch bump
  src/bitwarden_workflow_linter/rules/run_actionlint.py
Labels: version:patch

#104 [BRE-783] Test workflow linter with Windows runner
  .github/workflows/actionlint_windows.yml
  Pipfile
  Pipfile.lock
Labels: version:minor

#106 [BRE-783] Agalles/move actionlint version
  .github/CODEOWNERS
  .github/renovate.json
  .github/workflows/ci.yml
  src/bitwarden_workflow_linter/actionlint_version.yaml
  src/bitwarden_workflow_linter/rules/run_actionlint.py
  src/bitwarden_workflow_linter/utils.py
  tests/rules/test_run_actionlint.py
Labels: version:patch

#109 Agalles/pin actionlint version
  src/bitwarden_workflow_linter/rules/run_actionlint.py
  tests/rules/test_run_actionlint.py
Labels: version:minor
